import React, { Component } from 'react';
import { StyleSheet, Text, View, Platform, AsyncStorage } from 'react-native';
//NetInfo was separated from react-native
import NetInfo from "@react-native-community/netinfo";
import { GiftedChat, InputToolbar } from 'react-native-gifted-chat';
import KeyboardSpacer from 'react-native-keyboard-spacer';
import CustomActions from './CustomActions';
import MapView from 'react-native-maps';

//import firebase/firestore
const firebase = require('firebase');
require('firebase/firestore');

//main chat view
export default class Chat extends Component {

  constructor() {
    super()
    //connect to firestore
    if (!firebase.apps.length){
      firebase.initializeApp({
        apiKey: "AIzaSyCm7rBTAfptfThXjWQhkp_H2B4yJ94Csbk",
        authDomain: "chat-app-9ef43.firebaseapp.com",
        databaseURL: "https://chat-app-9ef43.firebaseio.com",
        projectId: "chat-app-9ef43",
        storageBucket: "chat-app-9ef43.appspot.com",
        messagingSenderId: "430643467945",
        appId: "1:430643467945:web:647c27b024b1ed29e13bb8",
        measurementId: "G-E4XCFDT292"
      });
    }
    //refernce collection
    this.referenceMessages = firebase.firestore().collection('messages');
    //get and store messages for chat
    this.state = {
      messages: [],
      isConnected: false,
    }
  }

  //puts user's name in nav bar
  static navigationOptions = ({ navigation }) => {
    return {
      title: navigation.state.params.name
    };
  };

  /**
   * updates message state when chat window is opened
   * @function onCollectionUpdate
   * @param {string} _id generated by database
   * @param {date} createdAt toDate()
   * @param {string} text message text
   * @param {object} user 
   * @param {string} user._id generated by database
   * @param {string} user.name name entered at start
   * @param {string} user.avatar randomly generated avatar
   * @param {string} image attached image
   * @param {number} location geographic location
  */
  onCollectionUpdate = (querySnapshot) => {
    const messages = [];
    querySnapshot.forEach((doc) => {
      let data = doc.data();
      messages.push({
        _id: data._id,
        createdAt: data.createdAt.toDate(),
        text: data.text,
        user: {
          _id: data.user._id,
          name: data.user.name,
          avatar: data.user.avatar,
        },
        image: data.image,
        location: data.location,
      });
    });
    this.setState({
      messages,
    });
  };

  /**
   * adds message to database
   * @function addMessage
   * @param {string} _id 
   * @param {date} createdAt toDate()
   * @param {string} text message text
   * @param {object} user 
   * @param {string} user._id generated by database
   * @param {string} user.name name entered at start
   * @param {string} user.avatar randomly generated avatar
   * @param {string} image attached image
   * @param {number} location geographic location
  */
  addMessage() {
    this.referenceMessages.add({
      _id: this.state.messages[0]._id,
      text: this.state.messages[0].text,
      createdAt: this.state.messages[0].createdAt,
      user: {
        _id: this.state.uid,
        name: this.props.navigation.state.params.name,
        avatar: 'https://placeimg.com/140/140/any'
      },
      image: this.state.messages[0].image,
      location: this.state.messages[0].location,
    });
  };

  /**
   * @function onSend
   * @param {*} messages defined in addMessage()
   * @returns {state} messages state updated with new message
  */
  onSend(messages = []) {
    this.setState(previousState => ({
      messages: GiftedChat.append(previousState.messages, messages),
    }),
      () => {
        this.addMessage();
        this.saveMessages();
      })
  };

  /**
   * async function for getting messages even when offline
   * @async
   * @function getMessages
   * @returns {Promise<string>} messages from async storage
   */  
  async getMessages() {
    let messages = '';
    try {
      messages = await AsyncStorage.getItem('messages') || [];
      this.setState({
        messages: JSON.parse(messages)
      });
    } catch (error) {
      console.log(error.message);
    }
  };

  /**
   * async function for saving messages even when offline
   * @async
   * @function saveMessages
   * @returns {Promise<string>} save messages to async storage
   */
  async saveMessages() {
    try {
      await AsyncStorage.setItem('messages', JSON.stringify(this.state.messages));
    } catch (error) {
      console.log(error.message);
    }
  }

  /**
   * async function for deleting messages from storage if needed
   * @async
   * @function deleteMessages
   * @returns {Promise<string>} delete messages from async storage
   */
  async deleteMessages() {
    try {
      await AsyncStorage.removeItem('messages');
    } catch (error) {
      console.log(error.message);
    }
  }


  componentDidMount() {
    NetInfo.fetch().then(isConnected => {
      if (isConnected == true) {
        console.log('online');
        this.setState({
          isConnected: true,
        });
        this.authUnsubscribe = firebase.auth().onAuthStateChanged(async (user) => {
          if (!user) {
            await firebase.auth().signInAnonymously();
          }
          this.setState({
            uid: user.uid,
            loggedInText: 'Hello there ${navigation.state.params.name}',
          });
          this.unsubscribe = this.referenceMessages.onSnapshot(this.onCollectionUpdate);
        });
      } else {
        console.log('offline');
        this.setState({
          isConnected: false,
        });
        this.getMessages();
      }
    });  
  }

  componentWillUnmount() {
    this.authUnsubscribe();
  }

  /**
   * No input toolbar rendered when offline
   * @function renderInputToolbar
   * @returns {InputToolbar}
   */
  renderInputToolbar(props) {
    if (this.state.isConnected == false) {
    } else {
      return(
        <InputToolbar {...props} />
      );
    }
  };

  renderCustomActions = (props) => {
    return <CustomActions {...props} />;
  };

  renderCustomView (props) {
    const { currentMessage } = props;
    if (currentMessage.location) {
      return (
        <MapView
          style={{
            width: 150,
            height: 100,
            borderRadius: 13,
            margin: 3
          }}
          region={{
            latitude: currentMessage.location.latitude,
            longitude: currentMessage.location.longitude,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
          }}
        />
      );
    }
    return null;
  }

  render() {
    return (
      <View style={[styles.container, {backgroundColor: this.props.navigation.state.params.roomColor}]}>
        <GiftedChat
          messages={this.state.messages}
          onSend={messages => this.onSend(messages)}
          user={{
            _id: 1,
          }}
          renderActions={this.renderCustomActions}
          renderCustomView={this.renderCustomView}
        />
        {Platform.OS === 'android' ? <KeyboardSpacer/> : null }
      </View>
    );
  }
}

/**
 * styles
 * @constant
 * @type {object}
 */
const styles = StyleSheet.create({
  container: {
    flex: 1,
    color: '#FFF',
  },
});